const newValidUser = {
  username: 'leon',
  email: 'o1ddss22@rvemold.com',
  lastname: 'Muller',
  firstname: 'Leon',
  password: 'Nena123',
  confirmPassword: 'Nena123',
  language: 'de',
};

const invalidUsers = [
  {
    username: 'leon',
    email: 'o1ddss22@rvemold.com',
    lastname: 'Muller',
    firstname: 'Leon',
    password: 'Nenaaaaaa',
    confirmPassword: 'Nenaaaaaa',
    language: 'de',
  },
  {
    username: 'leon',
    email: 'o1ddss22@rvemold.com',
    lastname: 'Muller',
    firstname: 'Leon',
    password: 'nena1234',
    confirmPassword: 'nena1234',
    language: 'de',
  },
  {
    username: 'leon',
    email: 'o1ddss22@rvemold.com',
    lastname: 'Muller',
    firstname: 'Leon',
    password: 'NENA1234',
    confirmPassword: 'NENA1234',
    language: 'de',
  },
  {
    username: 'leon',
    email: 'o1ddss22@rvemold.com',
    lastname: 'Muller',
    firstname: 'Leon',
    password: 'NENA1234',
    confirmPassword: 'Nena12',
    language: 'de',
  },
  {
    username: 'leon',
    email: 'o1ddss22rvemold.com',
    lastname: 'Muller',
    firstname: 'Leon',
    password: 'NENA1234',
    confirmPassword: 'Nena1234',
    language: 'de',
  },
  {
    username: 'leon',
    email: 'o1ddss22@rvemold.com',
    lastname: 'Muller',
    firstname: '!!!',
    password: 'NENA1234',
    confirmPassword: 'Nena1234',
    language: 'de',
  },
  {
    username: 'leon',
    email: 'o1ddss22@rvemold.com',
    lastname: '!__',
    firstname: 'Lena',
    password: 'NENA1234',
    confirmPassword: 'Nena1234',
    language: 'de',
  },
  {
    username: '!@@@',
    email: 'o1ddss22@rvemold.com',
    lastname: 'Lustig',
    firstname: 'Lena',
    password: 'NENA1234',
    confirmPassword: 'Nena1234',
    language: 'de',
  },
  {
    username: 'leon',
    email: 'o1ddssdsds22@rvemold.com',
    lastname: 'Lustig',
    firstname: 'Lala',
    password: 'Nena123',
    confirmPassword: 'Nena123',
    language: 'de',
  },
  {
    username: 'john',
    email: 'o1ddss22@rvemold.com',
    lastname: 'wayne',
    firstname: 'john',
    password: 'Nena123',
    confirmPassword: 'Nena123',
    language: 'de',
  },
];

export default {
  newValidUser,
  invalidUsers,
};
