# build environment
FROM node:15.3.0-alpine as build

ARG BACKEND_URL
ENV REACT_APP_BACKEND_URL $BACKEND_URL

WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./
RUN npm ci

# Bundle app source
COPY . .

RUN npm run build

# production environment
FROM nginx:1.19.5-alpine

COPY --from=build /usr/src/app/build /usr/share/nginx/html
COPY ./nginx-conf/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]