POST http://localhost:5003/api/users/ HTTP/1.1
content-Type: application/json

{
  "username": "leon",
  "email": "o1ddss22@rvemold.com",
  "lastname": "Muller",
  "firstname": "Leon",
  "password": "Nena123",
  "confirmPassword": "Nena123",
  "language": "de"
}