name: API Tests

on: push

jobs:
  run-linters:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 15
          
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: 4
          
      - name: Install Node.js dependencies
        run: |
          cd backend
          npm install
          
      - name: Run tests
        run: |
          cd backend
          npm test    
        env:
         CI: true
