name: API Tests

on: push

jobs:
  run-linters:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 15
          
      - name: Start Docker
        run: |
          make build
          make start
          
      - name: Install Node.js dependencies
        run: |
          cd backend
          npm install
          
      - name: Run tests
        run: make test-back
        env:
         CI: true
