name: API Tests

on: push

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 15
          
      - name: Create env file
        run: |
          touch .env
          echo BACKEND_PORT_DEV=3000 >> .env
          echo BACKEND_URL=http://localhost:3000 >> .env
          echo OMDB_KEY=2c600c89 >> .env
          echo FRONTEND_PORT_DEV=3001 >> .env
          echo SECRET=some_json_secret >> .env
          cat .env
          
      - name: Start Docker
        run: |
          make build
          make start
          docker-compose -f docker-compose.yml -p hypertube exec -T backend_hyper /bin/sh -c "npm test"
          
